version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security

  - package-ecosystem: "npm"
    directory: "/student-resource-hub"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security

  - package-ecosystem: "npm"
    directory: "/projects/email-campaign-builder"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
