ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS template VARCHAR(80),
  ADD COLUMN IF NOT EXISTS headline VARCHAR(120),
  ADD COLUMN IF NOT EXISTS body_text TEXT,
  ADD COLUMN IF NOT EXISTS cta_text VARCHAR(40);
