const messages=document.getElementById('messages');const form=document.getElementById('chatForm');const input=document.getElementById('input');
function add(text,type){const el=document.createElement('div');el.className=`msg ${type}`;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight}
const facts={
who:`Hanshit is a Polytechnic Computer Science student and student developer who uses this repository as a project portfolio and learning workspace. His documented approach is: Learn → Build → Improve → Repeat.`,
projects:`The repository currently documents three featured projects: Study Resource Manager, Student Productivity Dashboard, and C Student Record Management System. The first two have browser-based interfaces; the C project is a console-based C application with a live-demo version in the repository.`,
learning:`Hanshit is currently learning C Programming, JavaScript, Web Development, Git & GitHub, Computer Networks, and core Computer Science fundamentals. The profile also documents exploration of AI tools and prompt engineering.`,
repo:`Hanshit is a portfolio and learning workspace. It contains project code, learning resources, documentation, a visitor-facing Jems assistant, and GitHub Pages deployment configuration.`,
skills:`Documented skills include basic C, JavaScript and HTML/CSS learning, Git and GitHub workflow, Computer Networks learning, AI tools and prompt engineering exploration, and familiarity with Excel, Word, PowerPoint, Jira, Agile/Scrum, project planning, and risk management.`};
function answer(q){const s=q.toLowerCase();if(s.includes('who is hanshit')||s.includes('about hanshit'))return facts.who;if(s.includes('project'))return facts.projects;if(s.includes('learn'))return facts.learning;if(s.includes('repository')||s.includes('repo'))return facts.repo;if(s.includes('skill')||s.includes('technology')||s.includes('tech'))return facts.skills;if(s.includes('jems'))return `Jems is Hanshit's repository knowledge assistant. This visitor page answers from documented information in the repository rather than pretending to know undocumented facts.`;return `I can answer questions about Hanshit's documented profile, projects, skills, technologies, learning areas, repository structure, and Jems. Try asking: “What projects has Hanshit built?”`}
add(`Hi! I'm Jems — Hanshit Sir Assistant. Ask me about Hanshit, his projects, skills, learning journey, or this repository.`,`bot`);
function send(q){q=q.trim();if(!q)return;add(q,'user');setTimeout(()=>add(answer(q),'bot'),180);input.value='';input.focus()}
form.addEventListener('submit',e=>{e.preventDefault();send(input.value)});document.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.q)));
