(() => {"use strict";
const UUID_PATTERN=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const isValidUuid=value=>typeof value==="string"&&UUID_PATTERN.test(value);
const id=new URLSearchParams(window.location.search).get("id");
const valid=isValidUuid(id);
const title=document.querySelector("#campaign-title"),subject=document.querySelector("#campaign-subject"),status=document.querySelector("#campaign-status"),updated=document.querySelector("#campaign-updated"),audience=document.querySelector("#audience-name"),audienceMeta=document.querySelector("#audience-meta"),template=document.querySelector("#content-template"),summary=document.querySelector("#content-summary"),edit=document.querySelector("#edit-link"),content=document.querySelector("#content-link"),message=document.querySelector("#detail-message"),deleteButton=document.querySelector("#delete-campaign");
if(!valid){message.textContent="Invalid campaign link.";deleteButton.disabled=true;return;}
edit.href="./campaign-edit.html?id="+encodeURIComponent(id);content.href="./email-editor.html?id="+encodeURIComponent(id);
async function csrfToken(){const r=await fetch("../api/auth/csrf",{credentials:"same-origin"});if(!r.ok)throw new Error();const d=await r.json();if(typeof d.token!=="string")throw new Error();return d.token;}
async function load(){try{const r=await fetch("../api/campaigns/detail?id="+encodeURIComponent(id),{credentials:"same-origin"}),d=await r.json().catch(()=>({}));if(r.status===401){window.location.href="./login.html";return;}if(!r.ok)throw new Error();const c=d.campaign;title.textContent=c.name;subject.textContent=c.subject_line;status.textContent=c.status;updated.textContent="Updated "+new Date(c.updated_at).toLocaleString();audience.textContent=c.audience_name||c.audience||"No audience selected";audienceMeta.textContent=c.audience_name?c.audience_source+" · "+c.audience_condition:"Select an audience to continue.";template.textContent=c.template||"Not configured";summary.textContent=c.headline||"Add your email content to continue.";}catch{message.textContent="Campaign details could not be loaded.";}}
deleteButton.addEventListener("click",async()=>{if(!window.confirm("Delete this campaign permanently? This action cannot be undone."))return;deleteButton.disabled=true;message.textContent="Deleting campaign…";try{const token=await csrfToken();const r=await fetch("../api/campaigns/delete?id="+encodeURIComponent(id),{method:"DELETE",credentials:"same-origin",headers:{"X-CSRF-Token":token}});if(r.status===401){window.location.href="./login.html";return;}if(!r.ok)throw new Error();window.location.href="./campaigns.html";}catch{deleteButton.disabled=false;message.textContent="Campaign could not be deleted.";}});
load();
})();