const blank="<h2>Start building your PDF</h2><p>Type here, add images, create pages, and export when you're ready.</p>";const state={pages:[{html:blank,rotation:0,selected:false}],active:0,zoom:1,title:"Untitled document",history:[],future:[],importedPdf:false};const pageEl=document.querySelector("#page"),batchInput=document.querySelector("#pdf-batch-input"),renderLayer=document.querySelector("#pdf-render-layer"),pagesEl=document.querySelector("#pages"),statusEl=document.querySelector("#status"),zoomEl=document.querySelector("#zoom"),titleInput=document.querySelector("#title-input"),fileInput=document.querySelector("#file-input");
function snapshot(){return JSON.stringify({pages:state.pages,active:state.active,title:state.title})}function checkpoint(){state.history.push(snapshot());if(state.history.length>30)state.history.shift();state.future=[]}function sync(){state.pages[state.active].html=pageEl.innerHTML}async function renderRealThumbnails(){if(!state.importedBytes){realThumbsEl.hidden=true;return}realThumbsEl.hidden=false;realThumbsEl.innerHTML="<div class='muted'>Rendering thumbnails…</div>";try{const lib=await PDF_ENGINE.initPdfJs();const pdf=await lib.getDocument({data:new Uint8Array(state.importedBytes)}).promise;realThumbsEl.innerHTML="";for(let i=0;i<pdf.numPages;i++){const page=await pdf.getPage(i+1);const base=page.getViewport({scale:1});const viewport=page.getViewport({scale:112/base.width});const wrap=document.createElement("button");wrap.type="button";wrap.className="real-thumb "+(i===state.active?"active ":"")+(state.pages[i]?.selected?"selected":"");wrap.dataset.page=String(i);const canvas=document.createElement("canvas");canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);wrap.appendChild(canvas);const label=document.createElement("span");label.className="thumb-number";label.textContent="Page "+(i+1);wrap.appendChild(label);realThumbsEl.appendChild(wrap);await page.render({canvasContext:canvas.getContext("2d"),viewport}).promise}}catch(error){realThumbsEl.innerHTML="<div class='muted'>Unable to render PDF thumbnails.</div>"}}

realThumbsEl.addEventListener("click",e=>{const el=e.target.closest("[data-page]");if(!el)return;sync();const i=Number(el.dataset.page);if(e.ctrlKey||e.metaKey||e.shiftKey){state.pages[i].selected=!state.pages[i].selected;renderRealThumbnails();statusEl.textContent=state.pages.filter(p=>p.selected).length+" pages selected";return}state.active=i;render();statusEl.textContent="Page "+(i+1)+" selected"});

function renderPages(){pagesEl.innerHTML=state.pages.map((p,i)=>'<div class="page-thumb '+(i===state.active?"active ":"")+(p.selected?"selected":"")+'" data-page="'+i+'"><div class="thumb-paper">'+p.html+'</div><div class="page-number">Page '+(i+1)+'</div></div>').join("")}function updateButtons(){document.querySelector('[data-action="undo"]').disabled=!state.history.length;document.querySelector('[data-action="redo"]').disabled=!state.future.length}function render(){pageEl.innerHTML=state.pages[state.active].html;pageEl.style.zoom=state.zoom;titleInput.value=state.title;document.querySelector("#doc-title").textContent=state.title;zoomEl.textContent=Math.round(state.zoom*100)+"%";renderPages();updateButtons()}
function mutate(fn,label){sync();checkpoint();fn();render();statusEl.textContent=label}
pagesEl.addEventListener("dragstart",e=>{const el=e.target.closest("[data-page]");if(el)e.dataTransfer.setData("text/plain",el.dataset.page)});pagesEl.addEventListener("dragover",e=>{if(e.target.closest("[data-page]"))e.preventDefault()});pagesEl.addEventListener("drop",e=>{e.preventDefault();const target=e.target.closest("[data-page]");const from=Number(e.dataTransfer.getData("text/plain"));if(!target||Number.isNaN(from))return;const to=Number(target.dataset.page);if(from===to)return;sync();checkpoint();const [moved]=state.pages.splice(from,1);state.pages.splice(to,0,moved);state.active=to;render();statusEl.textContent="Page reordered"});pagesEl.addEventListener("click",e=>{const el=e.target.closest("[data-page]");if(!el)return;sync();state.active=Number(el.dataset.page);render();statusEl.textContent="Page "+(state.active+1)+" selected"});
pagesEl.addEventListener("contextmenu",e=>{const el=e.target.closest("[data-page]");if(!el)return;e.preventDefault();const i=Number(el.dataset.page);state.pages[i].selected=!state.pages[i].selected;renderPages();statusEl.textContent=state.pages.filter(p=>p.selected).length+" pages selected"});
pageEl.addEventListener("input",()=>{sync();statusEl.textContent="Editing…"});titleInput.addEventListener("input",()=>{state.title=titleInput.value||"Untitled document";document.querySelector("#doc-title").textContent=state.title});
document.querySelectorAll("[data-format]").forEach(b=>b.addEventListener("click",()=>{pageEl.focus();document.execCommand(b.dataset.format,false,null);sync()}));document.querySelector("#text-style").addEventListener("change",e=>{pageEl.focus();document.execCommand("formatBlock",false,e.target.value);sync()});
document.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",()=>{const a=b.dataset.action;
if(a==="add-page")mutate(()=>{state.pages.push({html:"<h2>New page</h2><p>Continue your document here.</p>"});state.active=state.pages.length-1},"Page added");
else if(a==="duplicate-page")mutate(()=>{state.pages.splice(state.active+1,0,{html:state.pages[state.active].html});state.active++},"Page duplicated");
else if(a==="clear-selection"){state.pages.forEach(p=>p.selected=false);renderPages();if(state.importedBytes)renderRealThumbnails();statusEl.textContent="Selection cleared"}else if(a==="select-all"){state.pages.forEach(p=>p.selected=true);renderPages();statusEl.textContent=state.pages.length+" pages selected"}\nelse if(a==="rotate-page")mutate(()=>{state.pages[state.active].rotation=((state.pages[state.active].rotation||0)+90)%360},"Page rotated");\nelse if(a==="export-selected"){const selected=state.pages.map((p,i)=>p.selected?i:-1).filter(i=>i>=0);if(!selected.length){statusEl.textContent="No pages selected";return}try{statusEl.textContent="Exporting selected pages…";const bytes=await PDF_ENGINE.exportSelected(state,selected);downloadPdf(bytes,"selected-pages.pdf");statusEl.textContent=selected.length+" pages exported"}catch(error){statusEl.textContent=error instanceof Error?error.message:"Export failed"}}else if(a==="delete-selected"){const selected=state.pages.filter(p=>p.selected).length;if(!selected){statusEl.textContent="No pages selected";return}if(selected>=state.pages.length){statusEl.textContent="Keep at least one page";return}mutate(()=>{state.pages=state.pages.filter(p=>!p.selected);state.active=Math.min(state.active,state.pages.length-1)},selected+" pages deleted")}else if(a==="rotate-selected"){const selected=state.pages.filter(p=>p.selected).length;if(!selected){statusEl.textContent="No pages selected";return}mutate(()=>{state.pages.forEach(p=>{if(p.selected)p.rotation=((p.rotation||0)+90)%360})},selected+" pages rotated")}else if(a==="delete-page"){if(state.pages.length===1){statusEl.textContent="A document needs at least one page";return}mutate(()=>{state.pages.splice(state.active,1);state.active=Math.min(state.active,state.pages.length-1)},"Page deleted")}
else if(a==="move-up"&&state.active>0)mutate(()=>{[state.pages[state.active-1],state.pages[state.active]]=[state.pages[state.active],state.pages[state.active-1]];state.active--},"Page moved");
else if(a==="move-down"&&state.active<state.pages.length-1)mutate(()=>{[state.pages[state.active+1],state.pages[state.active]]=[state.pages[state.active],state.pages[state.active+1]];state.active++},"Page moved");
else if(a==="insert-table")mutate(()=>{pageEl.innerHTML+='<table><tbody><tr><td>Cell 1</td><td>Cell 2</td><td>Cell 3</td></tr><tr><td>Cell 4</td><td>Cell 5</td><td>Cell 6</td></tr></tbody></table>';sync()},"Table inserted");
else if(a==="insert-page-break")mutate(()=>{pageEl.innerHTML+='<hr><p><strong>Page break</strong></p>';sync()},"Page break marker inserted");
else if(a==="insert-line")mutate(()=>{pageEl.innerHTML+="<hr>";sync()},"Divider inserted");
else if(a==="insert-link"){const url=window.prompt("Enter a web address (https://...)");if(url&&/^https?:\/\//i.test(url))mutate(()=>{pageEl.innerHTML+='<p><a href="'+url.replace(/"/g,"&quot;")+'" target="_blank" rel="noopener noreferrer">'+url.replace(/[<>]/g,"")+"</a></p>";sync()},"Link inserted")}
else if(a==="clear")mutate(()=>{state.pages=[{html:""}];state.active=0},"Document cleared");
else if(a==="new")mutate(()=>{state.pages=[{html:blank}];state.active=0;state.title="Untitled document"},"New document");
else if(a==="zoom-in"){state.zoom=Math.min(1.5,state.zoom+.1);render()}else if(a==="zoom-out"){state.zoom=Math.max(.6,state.zoom-.1);render()}
else if(a==="merge"||a==="split"){batchInput.multiple=a==="merge";batchInput.dataset.mode=a;batchInput.click()}\nelse if(a==="import"||a==="upload-image"){fileInput.accept=a==="import"?"application/pdf":"image/*";fileInput.click()}
else if(a==="undo"&&state.history.length){state.future.push(snapshot());Object.assign(state,JSON.parse(state.history.pop()));render();statusEl.textContent="Undone"}
else if(a==="redo"&&state.future.length){state.history.push(snapshot());Object.assign(state,JSON.parse(state.future.pop()));render();statusEl.textContent="Redone"}
else if(a==="export")exportPdf() }));
fileInput.addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;if(f.type.startsWith("image/")){const url=URL.createObjectURL(f);mutate(()=>{pageEl.innerHTML+='<p><img src="'+url+'" alt="" style="max-width:100%;height:auto"></p>';sync()},"Image added")}else statusEl.textContent="PDF import is queued for Phase 3 (PDF.js parser)";fileInput.value=""});

const originalImport=fileInput;fileInput.addEventListener("change",async e=>{const f=e.target.files?.[0];if(!f||f.type!=="application/pdf")return;try{statusEl.textContent="Loading PDF…";const bytes=await f.arrayBuffer();const count=await PDF_ENGINE.load(bytes);pageEl.hidden=true;renderLayer.hidden=false;await PDF_ENGINE.render(bytes,renderLayer,1);state.pages=Array.from({length:count},(_,i)=>({rotation:0,html:"<h3>Imported PDF page "+(i+1)+"</h3><p>Page preview loaded. Original PDF bytes are preserved for direct export.</p>"}));state.active=0;state.title=f.name.replace(/\.pdf$/i,"")||"Imported PDF";state.importedPdf=true;render();statusEl.textContent=count+" PDF page"+(count===1?"":"s")+" imported"}catch(err){console.error(err);statusEl.textContent="Could not open this PDF"}fileInput.value=""});
batchInput.addEventListener("change",async e=>{const files=[...(e.target.files||[])];if(!files.length)return;try{statusEl.textContent="Processing PDF…";if(batchInput.dataset.mode==="merge"){const out=await PDFLib.PDFDocument.create();for(const file of files){const src=await PDFLib.PDFDocument.load(await file.arrayBuffer());const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}const bytes=await out.save();downloadPdf(bytes,"merged-document");statusEl.textContent=files.length+" PDFs merged"}else{const src=await PDFLib.PDFDocument.load(await files[0].arrayBuffer());const total=src.getPageCount();const selected=window.prompt("Pages to extract (example: 1-3 or 2,4)");if(!selected)return;const indices=[];selected.split(",").forEach(part=>{const m=part.trim().match(/^(\d+)\s*-\s*(\d+)$/);if(m){const a=Number(m[1]),b=Number(m[2]);for(let n=Math.min(a,b);n<=Math.max(a,b);n++)if(n>=1&&n<=total)indices.push(n-1)}else{const n=Number(part.trim());if(n>=1&&n<=total)indices.push(n-1)}});const unique=[...new Set(indices)];if(!unique.length){statusEl.textContent="No valid pages selected";return}const out=await PDFLib.PDFDocument.create();const pages=await out.copyPages(src,unique);pages.forEach(p=>out.addPage(p));downloadPdf(await out.save(),"split-document");statusEl.textContent=unique.length+" pages extracted"} }catch(err){console.error(err);statusEl.textContent="PDF operation failed"}batchInput.value=""});function downloadPdf(bytes,name){const url=URL.createObjectURL(new Blob([bytes],{type:"application/pdf"}));const a=document.createElement("a");a.href=url;a.download=name+".pdf";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}\nasync function exportPdf(){try{pageEl.hidden=false;renderLayer.hidden=true;sync();statusEl.textContent="Preparing PDF…";let bytes;if(PDF_ENGINE.pdfDoc){bytes=await PDF_ENGINE.copySource()}else{bytes=await PDF_ENGINE.exportEditor(state.pages,state.title)}const blob=new Blob([bytes],{type:"application/pdf"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=(state.title||"document").replace(/[^a-z0-9-_ ]/gi,"").trim()||"document";a.download+=".pdf";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);statusEl.textContent="PDF exported"}catch(err){console.error(err);statusEl.textContent="PDF export failed"}}
render();\nfileInput.addEventListener("change",async e=>{const f=e.target.files?.[0];if(!f||f.type!=="application/pdf")return;try{statusEl.textContent="Loading PDF…";const bytes=await f.arrayBuffer();const count=await PDF_ENGINE.load(bytes);state.pages=Array.from({length:count},(_,i)=>({html:"<h3>Imported PDF page "+(i+1)+"</h3><p>Original PDF page loaded. Page-level editing is available for newly created content.</p>"}));state.active=0;state.title=f.name.replace(/\.pdf$/i,"")||"Imported PDF";render();statusEl.textContent=count+" PDF page"+(count===1?"":"s")+" imported"}catch(err){console.error(err);statusEl.textContent="Could not open this PDF"}fileInput.value=""});\nasync function exportPdf(){try{sync();statusEl.textContent="Preparing PDF…";const bytes=PDF_ENGINE.pdfDoc?await PDF_ENGINE.copySource():await PDF_ENGINE.exportEditor(state.pages,state.title);const blob=new Blob([bytes],{type:"application/pdf"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=((state.title||"document").replace(/[^a-z0-9-_ ]/gi,"").trim()||"document")+".pdf";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);statusEl.textContent="PDF exported"}catch(err){console.error(err);statusEl.textContent="PDF export failed"}}\nrender();