const blank="<h2>Start building your PDF</h2><p>Type here, add images, create pages, and export when you're ready.</p>";const state={pages:[{html:blank}],active:0,zoom:1,title:"Untitled document",history:[],future:[]};const pageEl=document.querySelector("#page"),pagesEl=document.querySelector("#pages"),statusEl=document.querySelector("#status"),zoomEl=document.querySelector("#zoom"),titleInput=document.querySelector("#title-input"),fileInput=document.querySelector("#file-input");
function snapshot(){return JSON.stringify({pages:state.pages,active:state.active,title:state.title})}function checkpoint(){state.history.push(snapshot());if(state.history.length>30)state.history.shift();state.future=[]}function sync(){state.pages[state.active].html=pageEl.innerHTML}function renderPages(){pagesEl.innerHTML=state.pages.map((p,i)=>'<div class="page-thumb '+(i===state.active?"active":"")+'" data-page="'+i+'"><div class="thumb-paper">'+p.html+'</div><div class="page-number">Page '+(i+1)+'</div></div>').join("")}function updateButtons(){document.querySelector('[data-action="undo"]').disabled=!state.history.length;document.querySelector('[data-action="redo"]').disabled=!state.future.length}function render(){pageEl.innerHTML=state.pages[state.active].html;pageEl.style.zoom=state.zoom;titleInput.value=state.title;document.querySelector("#doc-title").textContent=state.title;zoomEl.textContent=Math.round(state.zoom*100)+"%";renderPages();updateButtons()}
function mutate(fn,label){sync();checkpoint();fn();render();statusEl.textContent=label}
pagesEl.addEventListener("click",e=>{const el=e.target.closest("[data-page]");if(!el)return;sync();state.active=Number(el.dataset.page);render();statusEl.textContent="Page "+(state.active+1)+" selected"});
pageEl.addEventListener("input",()=>{sync();statusEl.textContent="Editing…"});titleInput.addEventListener("input",()=>{state.title=titleInput.value||"Untitled document";document.querySelector("#doc-title").textContent=state.title});
document.querySelectorAll("[data-format]").forEach(b=>b.addEventListener("click",()=>{pageEl.focus();document.execCommand(b.dataset.format,false,null);sync()}));document.querySelector("#text-style").addEventListener("change",e=>{pageEl.focus();document.execCommand("formatBlock",false,e.target.value);sync()});
document.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",()=>{const a=b.dataset.action;
if(a==="add-page")mutate(()=>{state.pages.push({html:"<h2>New page</h2><p>Continue your document here.</p>"});state.active=state.pages.length-1},"Page added");
else if(a==="duplicate-page")mutate(()=>{state.pages.splice(state.active+1,0,{html:state.pages[state.active].html});state.active++},"Page duplicated");
else if(a==="delete-page"){if(state.pages.length===1){statusEl.textContent="A document needs at least one page";return}mutate(()=>{state.pages.splice(state.active,1);state.active=Math.min(state.active,state.pages.length-1)},"Page deleted")}
else if(a==="move-up"&&state.active>0)mutate(()=>{[state.pages[state.active-1],state.pages[state.active]]=[state.pages[state.active],state.pages[state.active-1]];state.active--},"Page moved");
else if(a==="move-down"&&state.active<state.pages.length-1)mutate(()=>{[state.pages[state.active+1],state.pages[state.active]]=[state.pages[state.active],state.pages[state.active+1]];state.active++},"Page moved");
else if(a==="insert-table")mutate(()=>{pageEl.innerHTML+='<table><tbody><tr><td>Cell 1</td><td>Cell 2</td><td>Cell 3</td></tr><tr><td>Cell 4</td><td>Cell 5</td><td>Cell 6</td></tr></tbody></table>';sync()},"Table inserted");
else if(a==="insert-page-break")mutate(()=>{pageEl.innerHTML+='<hr><p><strong>Page break</strong></p>';sync()},"Page break marker inserted");
else if(a==="insert-line")mutate(()=>{pageEl.innerHTML+="<hr>";sync()},"Divider inserted");
else if(a==="insert-link"){const url=window.prompt("Enter a web address (https://...)");if(url&&/^https?:\/\//i.test(url))mutate(()=>{pageEl.innerHTML+='<p><a href="'+url.replace(/"/g,"&quot;")+'" target="_blank" rel="noopener noreferrer">'+url.replace(/[<>]/g,"")+"</a></p>";sync()},"Link inserted")}
else if(a==="clear")mutate(()=>{state.pages=[{html:""}];state.active=0},"Document cleared");
else if(a==="new")mutate(()=>{state.pages=[{html:blank}];state.active=0;state.title="Untitled document"},"New document");
else if(a==="zoom-in"){state.zoom=Math.min(1.5,state.zoom+.1);render()}else if(a==="zoom-out"){state.zoom=Math.max(.6,state.zoom-.1);render()}
else if(a==="import"||a==="upload-image"){fileInput.accept=a==="import"?"application/pdf":"image/*";fileInput.click()}
else if(a==="undo"&&state.history.length){state.future.push(snapshot());Object.assign(state,JSON.parse(state.history.pop()));render();statusEl.textContent="Undone"}
else if(a==="redo"&&state.future.length){state.history.push(snapshot());Object.assign(state,JSON.parse(state.future.pop()));render();statusEl.textContent="Redone"}
else if(a==="export")exportPdf() }));
fileInput.addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;if(f.type.startsWith("image/")){const url=URL.createObjectURL(f);mutate(()=>{pageEl.innerHTML+='<p><img src="'+url+'" alt="" style="max-width:100%;height:auto"></p>';sync()},"Image added")}else statusEl.textContent="PDF import is queued for Phase 3 (PDF.js parser)";fileInput.value=""});
function exportPdf(){sync();const w=window.open("","_blank");if(!w){statusEl.textContent="Allow pop-ups to export";return}w.document.write("<!doctype html><title>"+state.title.replace(/[<>]/g,"")+"</title><style>@page{size:A4;margin:0}body{margin:0;background:white}.page{width:794px;min-height:1123px;padding:72px;box-sizing:border-box;page-break-after:always;font-family:Arial,sans-serif;color:#202830}.page table{width:100%;border-collapse:collapse}.page td{border:1px solid #aaa;padding:8px}.page hr{border:0;border-top:1px solid #aaa}</style>");state.pages.forEach(p=>w.document.write('<section class="page">'+p.html+"</section>"));w.document.write("<script>window.onload=()=>window.print()<\\/script>");w.document.close();statusEl.textContent="Print dialog opened — choose Save as PDF"}render();