const seed=[{title:'Computer Networks Notes',subject:'Computer',type:'Notes',url:'https://www.geeksforgeeks.org/computer-network-tutorials/'},{title:'JavaScript Basics',subject:'Web Development',type:'Video',url:'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting'},{title:'C Programming Reference',subject:'C Programming',type:'Link',url:'https://en.cppreference.com/w/c'},{title:'Study Planning Guide',subject:'Productivity',type:'PDF',url:''}];
let resources=load('studyResources',seed), favOnly=false;
const $=id=>document.getElementById(id);
function load(k,f){try{const x=localStorage.getItem(k);const parsed=x?JSON.parse(x):f;return Array.isArray(parsed)?parsed:f}catch{return f}}
function save(){try{localStorage.setItem('studyResources',JSON.stringify(resources));return true}catch{return false}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function safeUrl(value){if(!value)return '';try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
function makeId(){return globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`}
function renderFilters(){const current=$('subjectFilter').value;const subjects=[...new Set(resources.map(r=>r.subject).filter(Boolean))].sort();$('subjectFilter').innerHTML='<option value="all">All subjects</option>'+subjects.map(s=>`<option value="${escapeHtml(s)}">${escapeHtml(s)}</option>`).join('');$('subjectFilter').value=subjects.includes(current)?current:'all'}
function render(){renderFilters();const q=$('searchInput').value.toLowerCase().trim(),subject=$('subjectFilter').value,type=$('typeFilter').value;const list=resources.filter(r=>(!q||`${r.title} ${r.subject} ${r.type}`.toLowerCase().includes(q))&&(subject==='all'||r.subject===subject)&&(type==='all'||r.type===type)&&(!favOnly||r.favorite));$('totalCount').textContent=resources.length;$('subjectCount').textContent=new Set(resources.map(r=>r.subject)).size;$('favoriteCount').textContent=resources.filter(r=>r.favorite).length;$('resultCount').textContent=`${list.length} result${list.length===1?'':'s'}`;$('emptyState').classList.toggle('hidden',list.length!==0);$('resourceGrid').innerHTML=list.map(r=>`<article class="card"><button class="fav" data-fav="${escapeHtml(r.id)}" aria-label="Toggle favorite">${r.favorite?'★':'☆'}</button><span class="badge">${escapeHtml(r.type)}</span><h3>${escapeHtml(r.title)}</h3><p class="muted">${escapeHtml(r.subject)}</p><div class="card-actions">${safeUrl(r.url)?`<a class="secondary" href="${escapeHtml(safeUrl(r.url))}" target="_blank" rel="noopener noreferrer">Open</a>`:'<button class="secondary" disabled>No link</button>'}<button class="secondary" data-delete="${escapeHtml(r.id)}">Delete</button></div></article>`).join('')}
$('resourceGrid').addEventListener('click',e=>{const fav=e.target.closest('[data-fav]'),del=e.target.closest('[data-delete]');if(fav){const r=resources.find(x=>x.id===fav.dataset.fav);if(r){r.favorite=!r.favorite;save();render()}}if(del){resources=resources.filter(x=>x.id!==del.dataset.delete);save();render()}});
$('addResourceBtn').onclick=()=>{$('resourceForm').reset();$('resourceDialog').showModal();$('titleInput').focus()};$('closeDialog').onclick=$('cancelBtn').onclick=()=>$('resourceDialog').close();$('resourceForm').addEventListener('submit',e=>{e.preventDefault();const url=$('urlInput').value.trim();const safe=safeUrl(url);if(url&&!safe){$('urlInput').setCustomValidity('Please enter a valid HTTP or HTTPS URL.');$('urlInput').reportValidity();return}$('urlInput').setCustomValidity('');resources.unshift({id:makeId(),title:$('titleInput').value.trim(),subject:$('subjectInput').value.trim(),type:$('typeInput').value,url:safe,favorite:false});save();$('resourceDialog').close();render()});
['searchInput','subjectFilter','typeFilter'].forEach(id=>$(id).addEventListener('input',render));$('favoritesFilter').onclick=()=>{favOnly=!favOnly;$('favoritesFilter').textContent=favOnly?'★ Favorites':'☆ Favorites';render()};$('themeToggle').onclick=()=>{document.body.classList.toggle('dark');try{localStorage.setItem('studyTheme',document.body.classList.contains('dark')?'dark':'light')}catch{}$('themeToggle').textContent=document.body.classList.contains('dark')?'☀':'☾'};try{if(localStorage.getItem('studyTheme')==='dark'){$('themeToggle').click()}}catch{}render();
