const resources=[
{title:"Computer Networks",subject:"Computer",chapter:"PAN, LAN, MAN & WAN",type:"Notes",description:"Network types explained with simple examples and comparisons."},
{title:"Functions & Arrays",subject:"Computer",chapter:"C Programming",type:"Notes",description:"A practical starting point for writing and understanding basic C programs."},
{title:"Laws of Force",subject:"Mechanics",chapter:"Force Systems",type:"Notes",description:"Core ideas, notation and the main laws used in first-year mechanics."},
{title:"Barriers to Communication",subject:"English",chapter:"Communication Skills",type:"Notes",description:"Short notes for revision, with everyday examples to make the topic clear."},
{title:"Introduction to AI",subject:"AI",chapter:"AI Fundamentals",type:"Study Guide",description:"Basic AI terminology and concepts before moving to advanced topics."},
{title:"Chemistry Fundamentals",subject:"Chemistry",chapter:"Engineering Chemistry",type:"Study Guide",description:"Organized first-year material for quick study and revision."}
];
const $=s=>document.querySelector(s);
const safe=(s,fn)=>{const el=$(s);if(el)fn(el)};
function loadPolish(){if(document.querySelector('link[href="./fixes.css"]'))return;const l=document.createElement("link");l.rel="stylesheet";l.href="./fixes.css";document.head.appendChild(l)}
function getStoredTheme(){try{return localStorage.getItem("srh-theme")}catch{return null}}
function saveTheme(value){try{localStorage.setItem("srh-theme",value)}catch{}}
function setTheme(){const saved=getStoredTheme();const preferred=window.matchMedia?.("(prefers-color-scheme:light)").matches?"light":"dark";const apply=value=>{document.documentElement.dataset.theme=value;safe("#theme-toggle",b=>{b.setAttribute("aria-pressed",String(value==="light"));b.setAttribute("aria-label",value==="light"?"Switch to dark theme":"Switch to light theme");b.textContent=value==="light"?"☾":"☼"})};apply(saved||preferred);safe("#theme-toggle",b=>{if(b.dataset.bound)return;b.dataset.bound="1";b.addEventListener("click",()=>{const next=document.documentElement.dataset.theme==="dark"?"light":"dark";apply(next);saveTheme(next)})})}
function setupNavigation(){const nav=document.querySelector(".nav");if(!nav)return;const links=[...nav.querySelectorAll("nav a")];const current=location.pathname.split("/").pop()||"index.html";links.forEach(a=>{if(a.getAttribute("href")?.split("/").pop()===current)a.setAttribute("aria-current","page")});let menu=nav.querySelector(".mobile-menu");if(!menu){const button=document.createElement("button");button.className="icon-button mobile-menu-toggle";button.type="button";button.setAttribute("aria-label","Open navigation");button.setAttribute("aria-expanded","false");button.textContent="☰";menu=document.createElement("div");menu.className="mobile-menu";menu.hidden=true;links.forEach(a=>{const clone=a.cloneNode(true);clone.addEventListener("click",()=>close());menu.appendChild(clone)});nav.appendChild(button);nav.appendChild(menu);const close=()=>{menu.hidden=true;button.setAttribute("aria-expanded","false");button.setAttribute("aria-label","Open navigation")};button.addEventListener("click",()=>{menu.hidden=!menu.hidden;button.setAttribute("aria-expanded",String(!menu.hidden));button.setAttribute("aria-label",menu.hidden?"Open navigation":"Close navigation")});document.addEventListener("click",e=>{if(!menu.hidden&&!nav.contains(e.target))close()})}if(!document.querySelector("footer.site-footer")){const footer=document.createElement("footer");footer.className="site-footer";footer.innerHTML=`<div class="container footer-inner"><div><strong>Student Resource Hub</strong><p>Focused academic resource discovery for students.</p></div><div class="footer-links"><a href="./index.html">Home</a><a href="./resources.html">Resources</a><a href="./features.html">Features</a><a href="./about.html">About</a><a href="./contact.html">Contact</a></div></div>`;document.body.appendChild(footer)}}
function setupResources(){const grid=$("#resource-grid"),filters=$("#filters"),search=$("#resource-search"),clear=$("#clear-search"),count=$("#count"),empty=$("#empty-state"),reset=$("#reset-filters");if(!grid||!filters||!search)return;let selected="All";["All",...new Set(resources.map(r=>r.subject))].forEach(subject=>{const b=document.createElement("button");b.type="button";b.className=`filter${subject===selected?" active":""}`;b.textContent=subject;b.setAttribute("aria-pressed",String(subject===selected));b.addEventListener("click",()=>{selected=subject;render()});filters.appendChild(b)});function render(){const term=search.value.trim().toLowerCase();const visible=resources.filter(r=>(selected==="All"||r.subject===selected)&&(!term||`${r.title} ${r.subject} ${r.chapter} ${r.description}`.toLowerCase().includes(term)));grid.innerHTML=visible.map(r=>{const id=resources.indexOf(r);return `<article class="card"><div class="card-meta"><span class="tag">${r.subject}</span><span>${r.type}</span></div><p class="chapter">${r.chapter}</p><h3>${r.title}</h3><p>${r.description}</p><div class="card-footer"><span>Resource details</span><a class="secondary-button" href="./resource.html?id=${id}">View</a></div></article>`}).join("");if(count)count.textContent=`${visible.length} of ${resources.length} resources`;if(empty)empty.hidden=visible.length!==0;if(clear)clear.hidden=search.value.length===0;filters.querySelectorAll("button").forEach(b=>{const active=b.textContent===selected;b.classList.toggle("active",active);b.setAttribute("aria-pressed",String(active))})}search.addEventListener("input",render);clear?.addEventListener("click",()=>{search.value="";render();search.focus()});reset?.addEventListener("click",()=>{selected="All";search.value="";render()});render()}
function setupSearch(){const input=$("#global-search"),suggestions=$("#search-suggestions");if(!input||!suggestions)return;function update(){const term=input.value.trim().toLowerCase();const list=term?resources.filter(r=>`${r.title} ${r.subject} ${r.chapter}`.toLowerCase().includes(term)):resources;suggestions.innerHTML=list.length?list.map(r=>`<a class="suggestion" href="./resource.html?id=${resources.indexOf(r)}"><strong>${r.title}</strong><small>${r.subject} · ${r.chapter}</small></a>`).join(""):"<p class=\"auth-note\">No matching resources.</p>"}input.addEventListener("input",update);update()}
function setupAuth(){safe("#auth-form",form=>form.addEventListener("submit",e=>{e.preventDefault();const status=$("#auth-status");if(!form.checkValidity()){form.reportValidity();if(status)status.textContent="Enter a valid email and a password of at least 6 characters.";return}if(status)status.textContent="Validation passed. Real account sign-in is handled by the full-stack application."}));document.querySelectorAll("[data-oauth]").forEach(b=>b.addEventListener("click",()=>safe("#auth-status",s=>s.textContent=`${b.dataset.oauth} sign-in is available in the full-stack application.`)))}
function setupContact(){safe("#contact-form",form=>form.addEventListener("submit",e=>{e.preventDefault();const status=$("#form-status");if(!form.checkValidity()){form.reportValidity();if(status)status.textContent="Please complete all fields correctly.";return}if(status){status.textContent="Message validated successfully. This static preview does not send data to a server.";status.classList.add("success")}form.reset()}))}
function setupDetails(){const title=$("#detail-title");if(!title)return;const raw=new URLSearchParams(location.search).get("id");const id=raw===null?NaN:Number(raw);const item=Number.isInteger(id)&&id>=0&&id<resources.length?resources[id]:null;if(!item){safe("#detail-subject",e=>e.textContent="RESOURCE NOT FOUND");safe("#detail-chapter",e=>e.textContent="");safe("#detail-title",e=>e.textContent="This resource could not be found.");safe("#detail-type",e=>e.textContent="Unavailable");safe("#detail-description",e=>e.textContent="The requested resource ID is invalid or no longer available. Return to the resource library to choose another item.");safe("#back-resources",e=>e.href="./resources.html");document.title="Resource Not Found — Student Resource Hub";return}safe("#detail-subject",e=>e.textContent=item.subject);safe("#detail-chapter",e=>e.textContent=item.chapter);safe("#detail-title",e=>e.textContent=item.title);safe("#detail-type",e=>e.textContent=item.type);safe("#detail-description",e=>e.textContent=item.description);safe("#back-resources",e=>e.href="./resources.html");document.title=`${item.title} — Student Resource Hub`}
function setupEffects(){const canvas=$("#aurora-canvas");if(!canvas)return;const ctx=canvas.getContext("2d",{alpha:true});if(!ctx)return;const reduced=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;let particles=[],raf=0,running=true;function resize(){const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);particles=Array.from({length:Math.min(32,Math.max(12,Math.floor(innerWidth/45)))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.5+.5,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.14,a:Math.random()*.35+.12}))}function draw(){if(!running)return;ctx.clearRect(0,0,innerWidth,innerHeight);const dark=document.documentElement.dataset.theme!=="light";particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=innerWidth;if(p.x>innerWidth)p.x=0;if(p.y<0)p.y=innerHeight;if(p.y>innerHeight)p.y=0;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=dark?`rgba(0,242,254,${p.a})`:`rgba(70,95,150,${p.a*.5})`;ctx.fill()});raf=requestAnimationFrame(draw)}resize();addEventListener("resize",resize);document.addEventListener("visibilitychange",()=>{running=!document.hidden;if(running&&!reduced){cancelAnimationFrame(raf);draw()}});if(!reduced)draw();else canvas.style.display="none";safe(".mockup-window",el=>{if(reduced)return;el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateY(${x*8}deg) rotateX(${y*-5}deg)`});el.addEventListener("pointerleave",()=>el.style.removeProperty("transform"))})}
function setupKeyboard(){document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();if(location.pathname.endsWith("search.html"))$("#global-search")?.focus();else location.href="./search.html"}if(e.key==="Escape")document.querySelectorAll(".mobile-menu:not([hidden])").forEach(m=>m.hidden=true)})}
loadPolish();setTheme();setupNavigation();setupResources();setupSearch();setupAuth();setupContact();setupDetails();setupEffects();setupKeyboard();
