const resources=[{title:"Computer Networks",subject:"Computer",chapter:"PAN, LAN, MAN & WAN",type:"Notes",description:"Network types explained with simple examples and comparisons."},{title:"Functions & Arrays",subject:"Computer",chapter:"C Programming",type:"Notes",description:"A practical starting point for writing and understanding basic C programs."},{title:"Laws of Force",subject:"Mechanics",chapter:"Force Systems",type:"Notes",description:"Core ideas, notation and the main laws used in first-year mechanics."},{title:"Barriers to Communication",subject:"English",chapter:"Communication Skills",type:"Notes",description:"Short notes for revision, with everyday examples to make the topic clear."},{title:"Introduction to AI",subject:"AI",chapter:"AI Fundamentals",type:"Study Guide",description:"Basic AI terminology and concepts before moving to advanced topics."},{title:"Chemistry Fundamentals",subject:"Chemistry",chapter:"Engineering Chemistry",type:"Study Guide",description:"Organized first-year material for quick study and revision."}];
const $=s=>document.querySelector(s);const grid=$("#resource-grid"),filters=$("#filters"),search=$("#resource-search"),clearSearch=$("#clear-search"),count=$("#count"),empty=$("#empty-state"),resetFilters=$("#reset-filters");let selected="All";
const subjects=["All",...new Set(resources.map(r=>r.subject))];subjects.forEach(subject=>{const b=document.createElement("button");b.type="button";b.className=`filter${subject===selected?" active":""}`;b.textContent=subject;b.setAttribute("aria-pressed",String(subject===selected));b.addEventListener("click",()=>{selected=subject;render()});filters.appendChild(b)});
function openModal(id){const item=resources[id];$("#modal-title").textContent=item.title;$("#modal-subject").textContent=item.subject;$("#modal-chapter").textContent=item.chapter;$("#modal-description").textContent=item.description;showModal($("#resource-modal"))}
function showModal(modal){modal.hidden=false;modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");const focus=modal.querySelector("button,input");if(focus)focus.focus()}
function hideModal(modal){modal.hidden=true;modal.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
$("#modal-close-button").addEventListener("click",()=>hideModal($("#resource-modal")));document.querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",()=>hideModal($("#resource-modal"))));
function render(){const term=search.value.trim().toLowerCase();const visible=resources.filter(r=>(selected==="All"||r.subject===selected)&&(!term||`${r.title} ${r.subject} ${r.chapter} ${r.description}`.toLowerCase().includes(term)));grid.innerHTML=visible.map(r=>{const id=resources.indexOf(r);return `<article class="card"><div class="card-meta"><span class="tag">${r.subject}</span><span>${r.type}</span></div><p class="chapter">${r.chapter}</p><h3>${r.title}</h3><p>${r.description}</p><div class="card-footer"><span>Preview resource</span><button type="button" data-resource-index="${id}">View</button></div></article>`}).join("");grid.querySelectorAll("[data-resource-index]").forEach(b=>b.addEventListener("click",()=>openModal(Number(b.dataset.resourceIndex))));count.textContent=`${visible.length} of ${resources.length}`;empty.hidden=visible.length!==0;clearSearch.hidden=search.value.length===0;filters.querySelectorAll("button").forEach(b=>{const active=b.textContent===selected;b.classList.toggle("active",active);b.setAttribute("aria-pressed",String(active))})}
search.addEventListener("input",render);clearSearch.addEventListener("click",()=>{search.value="";render();search.focus()});resetFilters.addEventListener("click",()=>{selected="All";search.value="";render();$("#resources").scrollIntoView({behavior:"smooth"})});
const searchModal=$("#search-modal"),globalSearch=$("#global-search"),suggestions=$("#search-suggestions");function updateSuggestions(){const term=globalSearch.value.trim().toLowerCase();const list=term?resources.filter(r=>`${r.title} ${r.subject} ${r.chapter}`.toLowerCase().includes(term)):resources.slice(0,5);suggestions.innerHTML=list.length?list.map(r=>`<button class="suggestion" type="button" data-id="${resources.indexOf(r)}"><strong>${r.title}</strong><small>${r.subject} · ${r.chapter}</small></button>`).join(""):"<p class=\"auth-note\">No matching resources.</p>";suggestions.querySelectorAll("[data-id]").forEach(b=>b.addEventListener("click",()=>{hideModal(searchModal);openModal(Number(b.dataset.id))}))}
function openSearch(){showModal(searchModal);globalSearch.value="";updateSuggestions();globalSearch.focus()}$("#hero-search").addEventListener("click",openSearch);globalSearch.addEventListener("input",updateSuggestions);document.querySelectorAll("[data-close-search]").forEach(el=>el.addEventListener("click",()=>hideModal(searchModal)));
const authModal=$("#auth-modal");$("#auth-open").addEventListener("click",()=>showModal(authModal));document.querySelectorAll("[data-close-auth]").forEach(el=>el.addEventListener("click",()=>hideModal(authModal)));
const savedTheme=localStorage.getItem("srh-theme");const preferred=window.matchMedia&&window.matchMedia("(prefers-color-scheme:light)").matches?"light":"dark";document.documentElement.dataset.theme=savedTheme||preferred;$("#theme-toggle").addEventListener("click",()=>{const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("srh-theme",next)});
$("#contact-form").addEventListener("submit",e=>{e.preventDefault();const form=e.currentTarget,status=$("#form-status");if(!form.checkValidity()){form.reportValidity();status.textContent="Please complete all fields correctly.";return}status.textContent="Thanks — your message passed validation. Connect this form to the full-stack API for real delivery.";form.reset()});
$("#auth-form").addEventListener("submit",e=>{e.preventDefault();const f=e.currentTarget,s=$("#auth-status");if(!f.checkValidity()){f.reportValidity();s.textContent="Enter a valid email and a password of at least 6 characters.";return}s.textContent="Frontend validation passed. Sign-in is completed by the full-stack app."});document.querySelectorAll("[data-oauth]").forEach(b=>b.addEventListener("click",()=>{$("#auth-status").textContent=`${b.dataset.oauth} OAuth is available in the full-stack application; this static preview does not fake an external login.`}));
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openSearch()}if(e.key==="Escape"){document.querySelectorAll(".modal:not([hidden])").forEach(m=>hideModal(m))}});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
const canvas=$("#aurora-canvas"),ctx=canvas.getContext("2d",{alpha:true});let particles=[];function resizeCanvas(){const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);particles=Array.from({length:Math.min(42,Math.max(18,Math.floor(innerWidth/35)))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.7+.5,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.18,a:Math.random()*.45+.15}))}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);const dark=document.documentElement.dataset.theme!=="light";particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=innerWidth;if(p.x>innerWidth)p.x=0;if(p.y<0)p.y=innerHeight;if(p.y>innerHeight)p.y=0;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=dark?`rgba(0,242,254,${p.a})`:`rgba(80,110,180,${p.a*.55})`;ctx.fill()});requestAnimationFrame(draw)}resizeCanvas();addEventListener("resize",resizeCanvas);draw();render();