const resources=[
{title:"Computer Networks",subject:"Computer",chapter:"PAN, LAN, MAN & WAN",type:"Notes",description:"Network types explained with simple examples and comparisons."},
{title:"Functions & Arrays",subject:"Computer",chapter:"C Programming",type:"Notes",description:"A practical starting point for writing and understanding basic C programs."},
{title:"Laws of Force",subject:"Mechanics",chapter:"Force Systems",type:"Notes",description:"Core ideas, notation and the main laws used in first-year mechanics."},
{title:"Barriers to Communication",subject:"English",chapter:"Communication Skills",type:"Notes",description:"Short notes for revision, with everyday examples to make the topic clear."},
{title:"Introduction to AI",subject:"AI",chapter:"AI Fundamentals",type:"Study Guide",description:"Basic AI terminology and concepts before moving to advanced topics."},
{title:"Chemistry Fundamentals",subject:"Chemistry",chapter:"Engineering Chemistry",type:"Study Guide",description:"Organized first-year material for quick study and revision."}
];
const $=s=>document.querySelector(s),safe=(s,fn)=>{const e=$(s);if(e)fn(e)};
const store={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
const bookmarks=()=>store.get("srh-bookmarks",[]),recent=()=>store.get("srh-recent",[]),progress=()=>store.get("srh-progress",{});
function loadPolish(){if(document.querySelector('link[href="./fixes.css"]'))return;const l=document.createElement("link");l.rel="stylesheet";l.href="./fixes.css";document.head.appendChild(l)}
function setTheme(){const saved=(()=>{try{return localStorage.getItem("srh-theme")}catch{return null}})();const preferred=window.matchMedia?.("(prefers-color-scheme:light)").matches?"light":"dark";const apply=v=>{document.documentElement.dataset.theme=v;safe("#theme-toggle",b=>{b.setAttribute("aria-pressed",String(v==="light"));b.setAttribute("aria-label",v==="light"?"Switch to dark theme":"Switch to light theme");b.textContent=v==="light"?"☾":"☼"})};apply(saved||preferred);safe("#theme-toggle",b=>b.addEventListener("click",()=>{const n=document.documentElement.dataset.theme==="dark"?"light":"dark";apply(n);try{localStorage.setItem("srh-theme",n)}catch{}}))}
function setupNavigation(){const nav=$(".nav");if(!nav)return;const links=[...nav.querySelectorAll("nav a")],current=location.pathname.split("/").pop()||"index.html";links.forEach(a=>{if(a.getAttribute("href")?.split("/").pop()===current)a.setAttribute("aria-current","page")});if(!nav.querySelector(".mobile-menu")){const b=document.createElement("button");b.className="icon-button mobile-menu-toggle";b.type="button";b.textContent="☰";b.setAttribute("aria-label","Open navigation");b.setAttribute("aria-expanded","false");const m=document.createElement("div");m.className="mobile-menu";m.hidden=true;const close=()=>{m.hidden=true;b.setAttribute("aria-expanded","false")};links.forEach(a=>{const c=a.cloneNode(true);c.addEventListener("click",close);m.appendChild(c)});nav.append(b,m);b.addEventListener("click",()=>{m.hidden=!m.hidden;b.setAttribute("aria-expanded",String(!m.hidden))});document.addEventListener("click",e=>{if(!m.hidden&&!nav.contains(e.target))close()})}if(!$("footer.site-footer")){const f=document.createElement("footer");f.className="site-footer";f.innerHTML='<div class="container footer-inner"><div><strong>Student Resource Hub</strong><p>Focused academic resource discovery for students.</p></div><div class="footer-links"><a href="./index.html">Home</a><a href="./resources.html">Resources</a><a href="./features.html">Features</a><a href="./about.html">About</a><a href="./contact.html">Contact</a></div></div>';document.body.appendChild(f)}}
function toggleBookmark(id){let a=bookmarks();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];store.set("srh-bookmarks",a);document.dispatchEvent(new CustomEvent("bookmarks-changed"));return a.includes(id)}
function markViewed(id){let a=recent().filter(x=>x!==id);a.unshift(id);store.set("srh-recent",a.slice(0,5))}
function complete(id){const p=progress();p[id]=100;store.set("srh-progress",p)}
function actions(id){const saved=bookmarks().includes(id);return `<div class="card-actions"><a class="secondary-button" href="./resource.html?id=${id}" data-view="${id}">Open</a><button class="secondary-button bookmark-button ${saved?"saved":""}" type="button" data-bookmark="${id}" aria-pressed="${saved}">${saved?"Saved":"Save"}</button></div>`}
function bind(root=document){root.querySelectorAll("[data-bookmark]").forEach(b=>b.addEventListener("click",()=>{const s=toggleBookmark(Number(b.dataset.bookmark));b.classList.toggle("saved",s);b.setAttribute("aria-pressed",String(s));b.textContent=s?"Saved":"Save"}));root.querySelectorAll("[data-view]").forEach(a=>a.addEventListener("click",()=>markViewed(Number(a.dataset.view))))}
function setupResources(){const grid=$("#resource-grid"),filters=$("#filters"),search=$("#resource-search");if(!grid||!filters||!search)return;let selected="All";if(!filters.children.length)["All",...new Set(resources.map(r=>r.subject))].forEach(s=>{const b=document.createElement("button");b.type="button";b.className=`filter${s==="All"?" active":""}`;b.textContent=s;b.setAttribute("aria-pressed",String(s==="All"));b.onclick=()=>{selected=s;render()};filters.appendChild(b)});function render(){const q=search.value.trim().toLowerCase(),visible=resources.map((r,id)=>({...r,id})).filter(r=>(selected==="All"||r.subject===selected)&&(!q||`${r.title} ${r.subject} ${r.chapter} ${r.description}`.toLowerCase().includes(q)));grid.innerHTML=visible.map(r=>`<article class="card"><div class="card-meta"><span class="tag">${r.subject}</span><span>${r.type}</span></div><p class="chapter">${r.chapter}</p><h3>${r.title}</h3><p>${r.description}</p><div class="card-footer"><span>Resource details</span>${actions(r.id)}</div></article>`).join("");safe("#count",e=>e.textContent=`${visible.length} of ${resources.length} resources`);safe("#empty-state",e=>e.hidden=visible.length>0);safe("#clear-search",e=>e.hidden=!search.value);filters.querySelectorAll("button").forEach(b=>{const a=b.textContent===selected;b.classList.toggle("active",a);b.setAttribute("aria-pressed",String(a))});bind(grid)}search.oninput=render;safe("#clear-search",b=>b.onclick=()=>{search.value="";render();search.focus()});safe("#reset-filters",b=>b.onclick=()=>{selected="All";search.value="";render()});render()}
function setupSearch(){const input=$("#global-search"),out=$("#search-suggestions");if(!input||!out)return;function render(){const q=input.value.trim().toLowerCase(),list=resources.map((r,id)=>({...r,id})).filter(r=>!q||`${r.title} ${r.subject} ${r.chapter}`.toLowerCase().includes(q));out.innerHTML=list.length?list.map(r=>`<a class="suggestion" href="./resource.html?id=${r.id}" data-view="${r.id}"><strong>${r.title}</strong><small>${r.subject} · ${r.chapter}</small></a>`).join(""):"<p class=\"auth-note\">No matching resources.</p>";bind(out)}input.oninput=render;render()}
function setupAuth(){safe("#auth-form",f=>f.onsubmit=e=>{e.preventDefault();const s=$("#auth-status");if(!f.checkValidity()){f.reportValidity();if(s)s.textContent="Enter a valid email and a password of at least 6 characters.";return}if(s)s.textContent="Validation passed. Real account sign-in is handled by the full-stack application."});document.querySelectorAll("[data-oauth]").forEach(b=>b.onclick=()=>safe("#auth-status",s=>s.textContent=`${b.dataset.oauth} sign-in is available in the full-stack application.`))}
function setupContact(){safe("#contact-form",f=>f.onsubmit=e=>{e.preventDefault();const s=$("#form-status");if(!f.checkValidity()){f.reportValidity();if(s)s.textContent="Please complete all fields correctly.";return}if(s){s.textContent="Message validated successfully. This static preview does not send data to a server.";s.classList.add("success")}f.reset()})}
function openPreview(item,id){let m=$("#resource-preview");if(!m){m=document.createElement("div");m.id="resource-preview";m.className="modal";m.hidden=true;m.innerHTML='<div class="modal-backdrop"></div><div class="modal-card glass-card" role="dialog" aria-modal="true" aria-labelledby="preview-title"><button class="modal-close" id="preview-close" type="button" aria-label="Close preview">×</button><p class="eyebrow">RESOURCE PREVIEW</p><h2 id="preview-title"></h2><p id="preview-meta" class="chapter"></p><p id="preview-body" class="hero-copy"></p><div class="preview-box"><strong>Preview mode</strong><p>The GitHub Pages version provides the catalog and preview interface. Actual PDF/video files can be connected through the separate full-stack resource library.</p></div></div>';document.body.appendChild(m);const close=()=>{m.hidden=true;document.body.classList.remove("modal-open")};$("#preview-close").onclick=close;m.querySelector(".modal-backdrop").onclick=close}$("#preview-title").textContent=item.title;$("#preview-meta").textContent=`${item.subject} · ${item.chapter} · ${item.type}`;$("#preview-body").textContent=item.description;m.hidden=false;document.body.classList.add("modal-open");complete(id)}
function setupDetails(){const title=$("#detail-title");if(!title)return;const id=Number(new URLSearchParams(location.search).get("id")),item=Number.isInteger(id)&&id>=0&&id<resources.length?resources[id]:null;if(!item){safe("#detail-subject",e=>e.textContent="RESOURCE NOT FOUND");title.textContent="This resource could not be found.";safe("#detail-type",e=>e.textContent="Unavailable");safe("#detail-description",e=>e.textContent="The requested resource is unavailable. Return to the library.");safe("#back-resources",e=>e.href="./resources.html");return}markViewed(id);["subject","chapter","title","type","description"].forEach(k=>safe(`#detail-${k}`,e=>e.textContent=item[k]));safe("#back-resources",e=>e.href="./resources.html");const box=$("#detail-actions");if(box){box.innerHTML=`<button class="primary-button" id="preview-resource" type="button">Preview resource</button>${actions(id)}`;$("#preview-resource").onclick=()=>openPreview(item,id);bind(box)}document.title=`${item.title} — Student Resource Hub`}
function setupHome(){if(!$(".hero"))return;const r=recent()[0]??0,item=resources[r]??resources[0],p=progress()[r]??0;let s=$("#student-progress");if(!s){s=document.createElement("section");s.id="student-progress";s.className="container section reveal";const main=$("main"),target=main?.querySelector("section:nth-of-type(2)");if(target)target.before(s);else main?.appendChild(s)}s.innerHTML=`<div class="section-heading"><div><p class="eyebrow">YOUR STUDY SPACE</p><h2>Continue learning.</h2></div><span class="count">${bookmarks().length} saved</span></div><div class="progress-card glass-card"><div><span class="tag">${item.subject}</span><p class="chapter">${recent().length?"Recently viewed":"Recommended starting point"}</p><h3>${item.title}</h3><p>${item.description}</p></div><div class="progress-side"><div class="progress-track"><span style="width:${p}%"></span></div><span>${p}% complete</span><a class="primary-button" href="./resource.html?id=${r}">Continue</a></div></div>`;let saved=$("#saved-resources");if(!saved){saved=document.createElement("section");saved.id="saved-resources";saved.className="container section";$("main")?.appendChild(saved)}function renderSaved(){const ids=bookmarks().filter(id=>resources[id]);saved.hidden=!ids.length;saved.innerHTML=ids.length?`<div class="section-heading"><div><p class="eyebrow">SAVED FOR LATER</p><h2>Your saved resources.</h2></div></div><div class="grid">${ids.map(id=>`<article class="card"><div class="card-meta"><span class="tag">${resources[id].subject}</span><span>${resources[id].type}</span></div><p class="chapter">${resources[id].chapter}</p><h3>${resources[id].title}</h3><p>${resources[id].description}</p><div class="card-footer"><span>Saved resource</span>${actions(id)}</div></article>`).join("")}</div>`:"";bind(saved)}renderSaved();document.addEventListener("bookmarks-changed",renderSaved)}
function setupEffects(){const c=$("#aurora-canvas");if(!c)return;const x=c.getContext("2d",{alpha:true});if(!x)return;const reduced=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;let ps=[],raf=0,running=true,mx=innerWidth/2,my=innerHeight/2;function resize(){const d=Math.min(devicePixelRatio||1,1.5);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0);ps=Array.from({length:Math.min(32,Math.max(12,Math.floor(innerWidth/45)))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.5+.5,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.14,a:Math.random()*.35+.12}))}function draw(){if(!running)return;x.clearRect(0,0,innerWidth,innerHeight);ps.forEach(p=>{p.x+=p.vx+(mx-innerWidth/2)*.000015;p.y+=p.vy+(my-innerHeight/2)*.000012;if(p.x<0)p.x=innerWidth;if(p.x>innerWidth)p.x=0;if(p.y<0)p.y=innerHeight;if(p.y>innerHeight)p.y=0;x.beginPath();x.arc(p.x,p.y,p.r,0,Math.PI*2);x.fillStyle=`rgba(0,242,254,${p.a})`;x.fill()});raf=requestAnimationFrame(draw)}resize();addEventListener("resize",resize);addEventListener("pointermove",e=>{mx=e.clientX;my=e.clientY});document.addEventListener("visibilitychange",()=>{running=!document.hidden;if(running&&!reduced){cancelAnimationFrame(raf);draw()}});if(!reduced)draw()}
function setup3D(){const targets=document.querySelectorAll(".hero-mockup,.mockup,.product-mockup,.interactive-mockup");if(!targets.length||window.matchMedia?.("(prefers-reduced-motion: reduce)").matches)return;targets.forEach(el=>{el.addEventListener("pointermove",e=>{const r=el.getBoundingClientRect(),rx=((e.clientY-r.top)/r.height-.5)*-7,ry=((e.clientX-r.left)/r.width-.5)*9;el.style.transform=`perspective(1100px) rotateX(${rx}deg) rotateY(${ry}deg) translateZ(0)`});el.addEventListener("pointerleave",()=>{el.style.transform=""})})}
function setupKeyboard(){document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();if(location.pathname.endsWith("search.html"))$("#global-search")?.focus();else location.href="./search.html"}if(e.key==="Escape"){$("#resource-preview")?.setAttribute("hidden","");document.body.classList.remove("modal-open")}})}
loadPolish();setTheme();setupNavigation();setupResources();setupSearch();setupAuth();setupContact();setupDetails();setupHome();setupEffects();setup3D();setupKeyboard();
