const KEY='studentos-planner-v1';
const defaults={subjects:[{name:'Computer',attendance:82},{name:'Mathematics',attendance:74},{name:'Physics',attendance:79}],assignments:[{title:'Computer Networks notes',date:'2026-09-18',done:false},{title:'Mechanics revision',date:'2026-09-20',done:false}],notes:'',studyMinutes:0};
const $=id=>document.getElementById(id);const clone=o=>JSON.parse(JSON.stringify(o));
let state=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||clone(defaults)}catch{return clone(defaults)}})();
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}};
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[c]));
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function render(){const avg=state.subjects.length?Math.round(state.subjects.reduce((a,s)=>a+s.attendance,0)/state.subjects.length):0;$('subjectCount').textContent=state.subjects.length;$('attendanceAverage').textContent=avg+'%';$('pendingCount').textContent=state.assignments.filter(a=>!a.done).length;$('studyMinutes').textContent=(state.studyMinutes||0)+'m';$('notes').value=state.notes||'';$('todayLabel').textContent=new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date());
$('subjectList').innerHTML=state.subjects.length?state.subjects.map((s,i)=>`<article class="subject-item"><div class="subject-row"><strong>${esc(s.name)}</strong><span>${s.attendance}%</span></div><div class="meter"><span style="width:${s.attendance}%"></span></div><button class="icon-btn" type="button" data-remove-subject="${i}">Remove</button></article>`).join(''):'<p class="hero-copy">No subjects yet. Add your first subject.</p>';
$('assignmentList').innerHTML=state.assignments.length?state.assignments.map((a,i)=>`<article class="assignment-item ${a.done?'done':''}"><div><strong>${esc(a.title)}</strong><small>${esc(a.date)}</small></div><button type="button" data-toggle-assignment="${i}">${a.done?'Undo':'Done'}</button></article>`).join(''):'<p class="hero-copy">No assignments yet. Add a task.</p>';
const best=state.subjects.slice().sort((a,b)=>b.attendance-a.attendance)[0];$('bestSubject').textContent=best?`${best.name} · ${best.attendance}%`:'—';const next=state.assignments.filter(a=>!a.done).sort((a,b)=>a.date.localeCompare(b.date))[0];$('nextDeadline').textContent=next?`${next.title} · ${next.date}`:'None';const focus=Math.round((avg+(state.assignments.length?100-state.assignments.filter(a=>!a.done).length/state.assignments.length*100:100))/2);$('overallPercent').textContent=focus+'%';$('focusHint').textContent=next?'Finish the next task':'Start a focus session'}

const slideLayer=$('slideLayer'),slideTitle=$('slideTitle'),slideContent=$('slideContent');
function openSlide(title,html){slideTitle.textContent=title;slideContent.innerHTML=html;slideLayer.classList.remove('closing');slideLayer.classList.add('open');slideLayer.setAttribute('aria-hidden','false');document.body.classList.add('slide-open');}
function closeSlide(){if(!slideLayer.classList.contains('open'))return;slideLayer.classList.add('closing');setTimeout(()=>{slideLayer.classList.remove('open','closing');slideLayer.setAttribute('aria-hidden','true');document.body.classList.remove('slide-open')},300)}
$('closeSlide').onclick=closeSlide;slideLayer.addEventListener('click',e=>{if(e.target===slideLayer)closeSlide()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSlide()});
function slideFor(kind){
  const avg=state.subjects.length?Math.round(state.subjects.reduce((a,s)=>a+s.attendance,0)/state.subjects.length):0;
  if(kind==='overview')openSlide('Overview',`<div class="slide-card"><h3>Academic overview</h3><p>Your planner currently tracks ${state.subjects.length} subjects with ${avg}% average attendance and ${state.assignments.filter(a=>!a.done).length} pending assignments.</p></div><div class="slide-card"><h3>Academic focus</h3><p>${$('overallPercent').textContent} overall focus score based on attendance and current work queue.</p></div>`);
  if(kind==='subjects')openSlide('Subjects & Attendance',`<div class="slide-card"><h3>Tracked subjects</h3><p>${state.subjects.length?state.subjects.map(s=>`${esc(s.name)} — ${s.attendance}% attendance`).join('<br>'):'No subjects added yet.'}</p></div><div class="slide-actions"><button class="btn primary" data-slide-action="add-subject">+ Add subject</button></div>`);
  if(kind==='assignments')openSlide('Assignments',`<div class="slide-card"><h3>Work queue</h3><p>${state.assignments.length?state.assignments.map(a=>`${esc(a.title)} — ${esc(a.date)}${a.done?' — completed':''}`).join('<br>'):'No assignments yet.'}</p></div><div class="slide-actions"><button class="btn primary" data-slide-action="add-assignment">+ Add task</button></div>`);
  if(kind==='focus')openSlide('Focus Lab',`<div class="slide-card"><h3>Study timer</h3><p>Current timer: ${$('timerDisplay').textContent}. Your tracked study time is ${state.studyMinutes||0} minutes.</p></div><div class="slide-actions"><button class="btn primary" data-slide-action="start">Start timer</button><button class="btn" data-slide-action="pause">Pause</button><button class="btn" data-slide-action="reset">Reset</button></div>`);
  if(kind==='notes')openSlide('Study Notes',`<div class="slide-card"><h3>Quick capture</h3><p>Your notes are stored locally in this browser.</p></div><textarea id="slideNotes" rows="10" placeholder="Write your study notes...">${esc(state.notes||'')}</textarea><div class="slide-actions"><button class="btn primary" data-slide-action="save-notes">Save notes</button></div>`);
  if(kind==='planner')openSlide('Planner',`<div class="slide-card"><h3>All-in-one academic workspace</h3><p>Manage subjects, attendance, assignments, study focus and notes from one place.</p></div><div class="slide-actions"><button class="btn primary" data-slide-action="subjects">View subjects</button><button class="btn" data-slide-action="assignments">View assignments</button></div>`);
  if(kind==='reset')openSlide('Reset Demo Data',`<div class="slide-card"><h3>Reset planner</h3><p>This restores the original demo subjects, assignments and notes. Your current local planner data will be replaced.</p></div><div class="slide-actions"><button class="btn primary" data-slide-action="confirm-reset">Reset now</button><button class="btn" data-slide-action="close">Cancel</button></div>`);
}

$('addSubject').onclick=()=>{$('subjectDialog').showModal();$('subjectName').focus()};$('addAssignment').onclick=()=>{$('assignmentDialog').showModal();$('assignmentTitle').focus()};
$('subjectForm').onsubmit=e=>{e.preventDefault();const name=$('subjectName').value.trim(),attendance=Number($('subjectAttendance').value);if(!name||attendance<0||attendance>100)return;$('subjectDialog').close();state.subjects.push({name,attendance});save();render();toast('Subject added');openSlide('Subject Added',`<div class="slide-card"><h3>${esc(name)}</h3><p>Attendance tracking started at ${attendance}%.</p></div>`)};
$('assignmentForm').onsubmit=e=>{e.preventDefault();const title=$('assignmentTitle').value.trim(),date=$('assignmentDate').value;if(!title||!date)return;$('assignmentDialog').close();state.assignments.push({title,date,done:false});save();render();toast('Assignment added');openSlide('Assignment Added',`<div class="slide-card"><h3>${esc(title)}</h3><p>Due date: ${esc(date)}.</p></div>`)};

document.addEventListener('click',e=>{const r=e.target.closest('[data-remove-subject]');if(r){state.subjects.splice(Number(r.dataset.removeSubject),1);save();render();toast('Subject removed');openSlide('Subject Removed','<div class="slide-card"><h3>Subject removed</h3><p>The planner has been updated successfully.</p></div>')}const a=e.target.closest('[data-toggle-assignment]');if(a){const i=Number(a.dataset.toggleAssignment);state.assignments[i].done=!state.assignments[i].done;save();render();toast(state.assignments[i].done?'Assignment completed':'Assignment reopened');openSlide(state.assignments[i].done?'Assignment Completed':'Assignment Reopened',`<div class="slide-card"><h3>${esc(state.assignments[i].title)}</h3><p>${state.assignments[i].done?'Marked as complete.':'Returned to the work queue.'}</p></div>`)}const action=e.target.closest('[data-slide-action]');if(action){const k=action.dataset.slideAction;if(k==='close')closeSlide();else if(k==='subjects')slideFor('subjects');else if(k==='assignments')slideFor('assignments');else if(k==='add-subject'){closeSlide();setTimeout(()=>$('addSubject').click(),320)}else if(k==='add-assignment'){closeSlide();setTimeout(()=>$('addAssignment').click(),320)}else if(k==='start')$('startTimer').click();else if(k==='pause')$('pauseTimer').click();else if(k==='reset')$('resetTimer').click();else if(k==='save-notes'){state.notes=$('slideNotes').value;save();render();toast('Notes saved');openSlide('Notes Saved','<div class="slide-card"><h3>Saved locally</h3><p>Your study notes are stored in this browser.</p></div>')}else if(k==='confirm-reset'){$('resetDemo').click();closeSlide()}}});

$('resetDemo').onclick=()=>{state=clone(defaults);save();render();toast('Demo data reset')};$('notes').oninput=e=>{state.notes=e.target.value;save();$('saveStatus').textContent='Saved locally'};
let remaining=1500,elapsed=0,timer=null;const updateTimer=()=>{$('timerDisplay').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;$('timerProgress').style.width=`${elapsed/1500*100}%`};$('startTimer').onclick=()=>{if(timer)return;$('timerLabel').textContent='Focus session running';timer=setInterval(()=>{if(remaining<=0){clearInterval(timer);timer=null;$('timerLabel').textContent='Session complete';toast('Focus session complete');openSlide('Session Complete','<div class="slide-card"><h3>Focus session complete</h3><p>Great work. Your focus session has finished.</p></div>');return}remaining--;elapsed++;if(elapsed%60===0){state.studyMinutes=(state.studyMinutes||0)+1;save();$('studyMinutes').textContent=state.studyMinutes+'m'}updateTimer()},1000);openSlide('Focus Session','<div class="slide-card"><h3>Timer running</h3><p>Stay focused. The planner is tracking this study session locally.</p></div>')};$('pauseTimer').onclick=()=>{clearInterval(timer);timer=null;$('timerLabel').textContent='Focus session paused';openSlide('Timer Paused','<div class="slide-card"><h3>Focus session paused</h3><p>You can resume whenever you are ready.</p></div>')};$('resetTimer').onclick=()=>{clearInterval(timer);timer=null;remaining=1500;elapsed=0;$('timerLabel').textContent='Focus session';updateTimer();openSlide('Timer Reset','<div class="slide-card"><h3>25:00</h3><p>The focus timer is ready for a fresh session.</p></div>')};
const applyTheme=v=>{document.body.dataset.theme=v;try{localStorage.setItem('studentos-theme',v)}catch{}$('themeToggle').setAttribute('aria-label',`Switch to ${v==='dark'?'light':'dark'} theme`);openSlide(v==='dark'?'Dark Theme':'Light Theme',`<div class="slide-card"><h3>${v==='dark'?'Dark':'Light'} mode enabled</h3><p>The planner appearance has been updated.</p></div>`)};let theme='dark';try{theme=localStorage.getItem('studentos-theme')||'dark'}catch{}document.body.dataset.theme=theme;$('themeToggle').setAttribute('aria-label',`Switch to ${theme==='dark'?'light':'dark'} theme`);$('themeToggle').onclick=()=>applyTheme(document.body.dataset.theme==='dark'?'light':'dark');

document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const target=a.getAttribute('href');if(target==='#overview')slideFor('overview');else if(target==='#subjects')slideFor('subjects');else if(target==='#assignments')slideFor('assignments');else if(target==='#focus')slideFor('focus')}));document.querySelector('[data-slide="planner"]').addEventListener('click',e=>{e.preventDefault();slideFor('planner')});document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();slideFor('overview')});
$('notes').addEventListener('focus',()=>openSlide('Study Notes','<div class="slide-card"><h3>Quick capture</h3><p>Continue writing in the main notes area, or use this slide for a focused notes view.</p></div>'));
updateTimer();render();