const KEY='studentos-planner-v1';
const defaults={subjects:[{name:'Computer',attendance:82},{name:'Mathematics',attendance:74},{name:'Physics',attendance:79}],assignments:[{title:'Computer Networks notes',date:'2026-09-18',done:false},{title:'Mechanics revision',date:'2026-09-20',done:false}],notes:'',studyMinutes:0};
const $=id=>document.getElementById(id);const clone=o=>JSON.parse(JSON.stringify(o));
let state=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||clone(defaults)}catch{return clone(defaults)}})();
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}};
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[c]));
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function render(){const avg=state.subjects.length?Math.round(state.subjects.reduce((a,s)=>a+s.attendance,0)/state.subjects.length):0;$('subjectCount').textContent=state.subjects.length;$('attendanceAverage').textContent=avg+'%';$('pendingCount').textContent=state.assignments.filter(a=>!a.done).length;$('studyMinutes').textContent=(state.studyMinutes||0)+'m';$('notes').value=state.notes||'';$('todayLabel').textContent=new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date());
$('subjectList').innerHTML=state.subjects.length?state.subjects.map((s,i)=>`<article class="subject-item"><div class="subject-row"><strong>${esc(s.name)}</strong><span>${s.attendance}%</span></div><div class="meter"><span style="width:${s.attendance}%"></span></div><button class="icon-btn" type="button" data-remove-subject="${i}">Remove</button></article>`).join(''):'<p class="hero-copy">No subjects yet. Add your first subject.</p>';
$('assignmentList').innerHTML=state.assignments.length?state.assignments.map((a,i)=>`<article class="assignment-item ${a.done?'done':''}"><div><strong>${esc(a.title)}</strong><small>${esc(a.date)}</small></div><button type="button" data-toggle-assignment="${i}">${a.done?'Undo':'Done'}</button></article>`).join(''):'<p class="hero-copy">No assignments yet. Add a task.</p>';
const best=state.subjects.slice().sort((a,b)=>b.attendance-a.attendance)[0];$('bestSubject').textContent=best?`${best.name} · ${best.attendance}%`:'—';const next=state.assignments.filter(a=>!a.done).sort((a,b)=>a.date.localeCompare(b.date))[0];$('nextDeadline').textContent=next?`${next.title} · ${next.date}`:'None';const focus=Math.round((avg+(state.assignments.length?100-state.assignments.filter(a=>!a.done).length/state.assignments.length*100:100))/2);$('overallPercent').textContent=focus+'%';$('focusHint').textContent=next?'Finish the next task':'Start a focus session'}
$('addSubject').onclick=()=>{$('subjectDialog').showModal();$('subjectName').focus()};$('addAssignment').onclick=()=>{$('assignmentDialog').showModal();$('assignmentTitle').focus()};
$('subjectForm').onsubmit=e=>{e.preventDefault();const name=$('subjectName').value.trim(),attendance=Number($('subjectAttendance').value);if(!name||attendance<0||attendance>100)return;$('subjectDialog').close();state.subjects.push({name,attendance});save();render();toast('Subject added')};
$('assignmentForm').onsubmit=e=>{e.preventDefault();const title=$('assignmentTitle').value.trim(),date=$('assignmentDate').value;if(!title||!date)return;$('assignmentDialog').close();state.assignments.push({title,date,done:false});save();render();toast('Assignment added')};
document.addEventListener('click',e=>{const r=e.target.closest('[data-remove-subject]');if(r){state.subjects.splice(Number(r.dataset.removeSubject),1);save();render();toast('Subject removed')}const a=e.target.closest('[data-toggle-assignment]');if(a){const i=Number(a.dataset.toggleAssignment);state.assignments[i].done=!state.assignments[i].done;save();render();toast(state.assignments[i].done?'Assignment completed':'Assignment reopened')}});
$('resetDemo').onclick=()=>{state=clone(defaults);save();render();toast('Demo data reset')};$('notes').oninput=e=>{state.notes=e.target.value;save();$('saveStatus').textContent='Saved locally'};
let remaining=1500,elapsed=0,timer=null;const updateTimer=()=>{$('timerDisplay').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;$('timerProgress').style.width=`${elapsed/1500*100}%`};$('startTimer').onclick=()=>{if(timer)return;$('timerLabel').textContent='Focus session running';timer=setInterval(()=>{if(remaining<=0){clearInterval(timer);timer=null;$('timerLabel').textContent='Session complete';toast('Focus session complete');return}remaining--;elapsed++;if(elapsed%60===0){state.studyMinutes=(state.studyMinutes||0)+1;save();$('studyMinutes').textContent=state.studyMinutes+'m'}updateTimer()},1000)};$('pauseTimer').onclick=()=>{clearInterval(timer);timer=null;$('timerLabel').textContent='Focus session paused'};$('resetTimer').onclick=()=>{clearInterval(timer);timer=null;remaining=1500;elapsed=0;$('timerLabel').textContent='Focus session';updateTimer()};
const applyTheme=v=>{document.body.dataset.theme=v;try{localStorage.setItem('studentos-theme',v)}catch{}$('themeToggle').setAttribute('aria-label',`Switch to ${v==='dark'?'light':'dark'} theme`)};let theme='dark';try{theme=localStorage.getItem('studentos-theme')||'dark'}catch{}applyTheme(theme);$('themeToggle').onclick=()=>applyTheme(document.body.dataset.theme==='dark'?'light':'dark');updateTimer();render();